/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.paresVistaControl.modificarOperadorEnTurno;

import javax.swing.DefaultListModel;

/**
 *
 * @author elena
 */
public class VistaModificarOperadorEnTurno extends javax.swing.JFrame {

    public CtrlVistaModificarOperadorEnTurno control;
    DefaultListModel modeloOperadoresEnTurno = new DefaultListModel();
    DefaultListModel modeloOperadoresACambiar = new DefaultListModel();

    /**
     * Creates new form VistaInicioSesion
     */
    public VistaModificarOperadorEnTurno() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new CtrlVistaModificarOperadorEnTurno(this);
        listaOperadoresEnTurno.setModel(modeloOperadoresEnTurno);
        listaOperadoresACambiar.setModel(modeloOperadoresACambiar);
        listaOperadoresACambiar.setEnabled(false);
        botonSolicitarCambio.setEnabled(false);
        botonConfirmarCambio.setEnabled(false);
        botonRechazarCambio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filtroTipoDeTurno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textoFechaSelec = new javax.swing.JTextField();
        botonMostrarTurnos = new javax.swing.JToggleButton();
        mensajeErr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOperadoresEnTurno = new javax.swing.JList<>();
        botonCancelar = new javax.swing.JButton();
        botonSolicitarCambio = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaOperadoresACambiar = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonConfirmarCambio = new javax.swing.JToggleButton();
        botonRechazarCambio = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(485, 287));

        jPanel1.setMinimumSize(new java.awt.Dimension(485, 287));

        filtroTipoDeTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DeMañana7", "DeTarde15", "DeNoche23" }));
        filtroTipoDeTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroTipoDeTurnoItemStateChanged(evt);
            }
        });
        filtroTipoDeTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTipoDeTurnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MODIFICAR OPERADOR EN TURNO");

        textoFechaSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFechaSelecActionPerformed(evt);
            }
        });

        botonMostrarTurnos.setText("Mostrar turnos");
        botonMostrarTurnos.setAlignmentX(0.5F);
        botonMostrarTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTurnosActionPerformed(evt);
            }
        });

        mensajeErr.setForeground(new java.awt.Color(255, 51, 0));
        mensajeErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listaOperadoresEnTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        listaOperadoresEnTurno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaOperadoresEnTurno);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonSolicitarCambio.setText("SolicitarCambio");
        botonSolicitarCambio.setAlignmentX(0.5F);
        botonSolicitarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSolicitarCambioActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listaOperadoresACambiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        listaOperadoresACambiar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaOperadoresACambiar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaOperadoresACambiarFocusGained(evt);
            }
        });
        listaOperadoresACambiar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listaOperadoresACambiarPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(listaOperadoresACambiar);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Operador Actual");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nuevo operador");

        botonConfirmarCambio.setText("Confirmar");
        botonConfirmarCambio.setAlignmentX(0.5F);
        botonConfirmarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarCambioActionPerformed(evt);
            }
        });

        botonRechazarCambio.setText("Rechazar");
        botonRechazarCambio.setAlignmentX(0.5F);
        botonRechazarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRechazarCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mensajeErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSolicitarCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(212, 212, 212))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(botonConfirmarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRechazarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonMostrarTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filtroTipoDeTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoFechaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(428, 428, 428))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTipoDeTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonMostrarTurnos)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSolicitarCambio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConfirmarCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRechazarCambio)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTurnosActionPerformed
        control.procesaSeleccionarFecha();
    }//GEN-LAST:event_botonMostrarTurnosActionPerformed

    private void textoFechaSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFechaSelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFechaSelecActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        control.finalizarCU();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonSolicitarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSolicitarCambioActionPerformed
        control.procesaSeleccionOperador();
        listaOperadoresACambiar.setEnabled(true);
    }//GEN-LAST:event_botonSolicitarCambioActionPerformed

    private void filtroTipoDeTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroTipoDeTurnoItemStateChanged

    }//GEN-LAST:event_filtroTipoDeTurnoItemStateChanged

    private void filtroTipoDeTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTipoDeTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTipoDeTurnoActionPerformed

    private void botonConfirmarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarCambioActionPerformed
        control.procesaConfirmarCambio();
    }//GEN-LAST:event_botonConfirmarCambioActionPerformed

    private void listaOperadoresACambiarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listaOperadoresACambiarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_listaOperadoresACambiarPropertyChange

    private void listaOperadoresACambiarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaOperadoresACambiarFocusGained
        botonConfirmarCambio.setEnabled(true);
        botonRechazarCambio.setEnabled(true);
    }//GEN-LAST:event_listaOperadoresACambiarFocusGained

    private void botonRechazarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRechazarCambioActionPerformed
        resetearListaOperadoresACambiar();
    }//GEN-LAST:event_botonRechazarCambioActionPerformed

    public String getFecha() {
        return textoFechaSelec.getText();
    }

    public void deshabilitarSeleccion() {
        botonSolicitarCambio.setEnabled(false);
        listaOperadoresEnTurno.setEnabled(false);
    }

    public void muestraMensajeError(String mensaje) {
        mensajeErr.setText(mensaje);
        resetearFecha();
    }

    public void muestraMensajeErrorSinResetearVista(String mensaje) {
        mensajeErr.setText(mensaje);
    }

    public void resetearFecha() {
        textoFechaSelec.setText("");
    }

    public void fijarFecha() {
        textoFechaSelec.setEditable(false);
    }

    public void habilitarSeleccionOperador() {
        botonSolicitarCambio.setEnabled(true);
    }

    public void fijarFiltro() {
        filtroTipoDeTurno.setEnabled(false);
    }

    public void agregarOperadorEnTurnoALista(String operador) {
        modeloOperadoresEnTurno.addElement(operador);
    }

    public void agregarOperadorACambiarALista(String operador) {
        modeloOperadoresACambiar.addElement(operador);
    }

    public String getOperadorSeleccionado() {
        return listaOperadoresEnTurno.getSelectedValue();
    }

    public String getOperadorACambiar() {
        return listaOperadoresACambiar.getSelectedValue();
    }

    public void desabilitarBotonMostrarTurnos() {
        botonMostrarTurnos.setEnabled(false);
    }

    public String getFiltroTipoDeTurno() {
        return filtroTipoDeTurno.getSelectedItem().toString();
    }
    
    public void resetearListaOperadoresACambiar(){
        modeloOperadoresACambiar.clear();
        listaOperadoresEnTurno.setEnabled(true);
        listaOperadoresACambiar.setEnabled(false);
        botonConfirmarCambio.setEnabled(false);
        botonRechazarCambio.setEnabled(false);
        habilitarSeleccionOperador();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarOperadorEnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarOperadorEnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarOperadorEnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarOperadorEnTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarOperadorEnTurno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JToggleButton botonConfirmarCambio;
    private javax.swing.JToggleButton botonMostrarTurnos;
    private javax.swing.JToggleButton botonRechazarCambio;
    private javax.swing.JToggleButton botonSolicitarCambio;
    private javax.swing.JComboBox<String> filtroTipoDeTurno;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaOperadoresACambiar;
    private javax.swing.JList<String> listaOperadoresEnTurno;
    private javax.swing.JLabel mensajeErr;
    private javax.swing.JTextField textoFechaSelec;
    // End of variables declaration//GEN-END:variables

}
