/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.paresVistaControl.atenderLlamada;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class VistaAtenderLlamada extends javax.swing.JFrame {
    public CtrlVistaAtenderLlamada control;
    /**
     * Creates new form VistaInicioSesion
     */
    public VistaAtenderLlamada() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new CtrlVistaAtenderLlamada(this);
        panelDescripcionEmergencia.setVisible(false);
        panelConfirmarDatos.setVisible(false);
        panelConsejos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonRegistrarLlamadaEntrante = new javax.swing.JToggleButton();
        panelConfirmarDatos = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        telefOrigenTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        comunicanteTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        polizaTextField = new javax.swing.JTextField();
        nombrePacienteTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        apellidosPacienteTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        fechaNacimientoTextField = new javax.swing.JTextField();
        filtroSexo = new javax.swing.JComboBox<>();
        botonConfirmarDatos = new javax.swing.JToggleButton();
        panelDescripcionEmergencia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextField = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        botonIntroducirDescripcion = new javax.swing.JToggleButton();
        criticaCheck = new java.awt.Checkbox();
        mensajeErr = new javax.swing.JLabel();
        panelConsejos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        descripcionConsejoTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        resultadoConsejoTextField = new javax.swing.JTextField();
        botonGuardarConsejo = new javax.swing.JToggleButton();
        mensajeConsejos = new javax.swing.JLabel();
        requiereOperativo = new java.awt.Checkbox();
        solucionaCheck = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ATENDER LLAMADA ENTRANTE");

        botonRegistrarLlamadaEntrante.setText("Registrar llamada entrante");
        botonRegistrarLlamadaEntrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarLlamadaEntranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(botonRegistrarLlamadaEntrante, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistrarLlamadaEntrante)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("- Teléfono de origen:  ");

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("- Nombre Comunicante:");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("- Número Poliza:");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("- Nombre Paciente:");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("- Apellidos Paciente:");

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("- Sexo:");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("- Fecha de nacimiento:");

        filtroSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        filtroSexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroSexoItemStateChanged(evt);
            }
        });
        filtroSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroSexoActionPerformed(evt);
            }
        });

        botonConfirmarDatos.setText("Confirmar datos");
        botonConfirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfirmarDatosLayout = new javax.swing.GroupLayout(panelConfirmarDatos);
        panelConfirmarDatos.setLayout(panelConfirmarDatosLayout);
        panelConfirmarDatosLayout.setHorizontalGroup(
            panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelConfirmarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaNacimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConfirmarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombrePacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConfirmarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(polizaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefOrigenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comunicanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarDatosLayout.createSequentialGroup()
                        .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosPacienteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmarDatosLayout.createSequentialGroup()
                                .addComponent(filtroSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))))
                .addGap(272, 272, 272))
            .addGroup(panelConfirmarDatosLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(botonConfirmarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConfirmarDatosLayout.setVerticalGroup(
            panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmarDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(telefOrigenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(comunicanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(polizaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(nombrePacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(apellidosPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(filtroSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfirmarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(fechaNacimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonConfirmarDatos)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        descripcionTextField.setColumns(20);
        descripcionTextField.setRows(5);
        descripcionTextField.setToolTipText("");
        jScrollPane1.setViewportView(descripcionTextField);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Descripción de la emergencia");

        botonIntroducirDescripcion.setText("Introducir datos emergencia");
        botonIntroducirDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroducirDescripcionActionPerformed(evt);
            }
        });

        criticaCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criticaCheck.setLabel("Crítica");

        javax.swing.GroupLayout panelDescripcionEmergenciaLayout = new javax.swing.GroupLayout(panelDescripcionEmergencia);
        panelDescripcionEmergencia.setLayout(panelDescripcionEmergenciaLayout);
        panelDescripcionEmergenciaLayout.setHorizontalGroup(
            panelDescripcionEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionEmergenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelDescripcionEmergenciaLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(panelDescripcionEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(botonIntroducirDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(panelDescripcionEmergenciaLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(criticaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionEmergenciaLayout.setVerticalGroup(
            panelDescripcionEmergenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionEmergenciaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(criticaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIntroducirDescripcion)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mensajeErr.setForeground(new java.awt.Color(255, 51, 51));
        mensajeErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeErr.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Consejos Otorgados");

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("- Descripción: ");

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("- Resultado:");

        botonGuardarConsejo.setText("Guardar consejo");
        botonGuardarConsejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarConsejoActionPerformed(evt);
            }
        });

        mensajeConsejos.setForeground(new java.awt.Color(255, 51, 51));
        mensajeConsejos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeConsejos.setText(" ");

        requiereOperativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        requiereOperativo.setLabel("Requiere operativo\n");

        solucionaCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        solucionaCheck.setLabel("Soluciona");

        javax.swing.GroupLayout panelConsejosLayout = new javax.swing.GroupLayout(panelConsejos);
        panelConsejos.setLayout(panelConsejosLayout);
        panelConsejosLayout.setHorizontalGroup(
            panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mensajeConsejos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelConsejosLayout.createSequentialGroup()
                .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsejosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsejosLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(descripcionConsejoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConsejosLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(31, 31, 31)
                                .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonGuardarConsejo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoConsejoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelConsejosLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solucionaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requiereOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelConsejosLayout.setVerticalGroup(
            panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsejosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(descripcionConsejoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(resultadoConsejoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(solucionaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiereOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarConsejo)
                .addGap(18, 18, 18)
                .addComponent(mensajeConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mensajeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDescripcionEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelConfirmarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConsejos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(mensajeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConfirmarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(panelConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescripcionEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarLlamadaEntranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarLlamadaEntranteActionPerformed
        control.procesaRegistrarLlamadaEntrante();
    }//GEN-LAST:event_botonRegistrarLlamadaEntranteActionPerformed

    private void filtroSexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroSexoItemStateChanged

    }//GEN-LAST:event_filtroSexoItemStateChanged

    private void filtroSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroSexoActionPerformed

    private void botonConfirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarDatosActionPerformed
        control.procesaConfirmarDatos();
    }//GEN-LAST:event_botonConfirmarDatosActionPerformed

    private void botonIntroducirDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroducirDescripcionActionPerformed
        control.procesaIntroducirDescripcion();
    }//GEN-LAST:event_botonIntroducirDescripcionActionPerformed

    private void botonGuardarConsejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarConsejoActionPerformed
        control.procesaGuardarConsejo();
    }//GEN-LAST:event_botonGuardarConsejoActionPerformed

    public void muestraMensajeError(String err){
        mensajeErr.setText(err);
    }
    
    public void habilitarConfirmarDatos(){
        panelConfirmarDatos.setVisible(true);
    }
    
    public void habilitarDescripcionEmergencia(){
        panelDescripcionEmergencia.setVisible(true);
    }
    
    public void habilitarConsejos(){
        panelConsejos.setVisible(true);
    }
    
    public String getDescripcionEmergencia(){
        return descripcionTextField.getText();
    }
    
    public boolean esCritica(){
        return criticaCheck.getState();
    }
    
    public String getDescripcionConsejo(){
        return descripcionConsejoTextField.getText();
    }
    
    public String getResultadoConsejo(){
        return resultadoConsejoTextField.getText();
    }
    
    public boolean getSolucionaConsejo(){
        return solucionaCheck.getState();
    }
    
    public void fijarDescripcionEmergencia(){
        descripcionTextField.setEditable(false);
        criticaCheck.setEnabled(false);
        botonIntroducirDescripcion.setEnabled(false);
    }
    
    
    public void fijarDatosInicioLlamada(){
        botonConfirmarDatos.setEnabled(false);
        apellidosPacienteTextField.setEditable(false);
        comunicanteTextField.setEditable(false);
        fechaNacimientoTextField.setEditable(false);
        filtroSexo.setEnabled(false);
        nombrePacienteTextField.setEditable(false);
        polizaTextField.setEditable(false);
        telefOrigenTextField.setEditable(false);
    }
    
    public void activacionOperativo(){
        JOptionPane.showMessageDialog(rootPane, "Llamada almacenada con éxito (CU ACTIVAR OPERATIVO NO IMPLEMENTADO)");
    }
    
    public void redirijirLlamada(){
        JOptionPane.showMessageDialog(rootPane, "Redirija llamada al 112 (CU FINALIZADO)");
    }
    
    public void llamadaFinalizadaConExito(){
        JOptionPane.showMessageDialog(rootPane,"La llamada se ha almacenado con éxito");
    }
    
    public String getTelefOrigen(){
        return telefOrigenTextField.getText();
    }
    
    public String getComunicante(){
        return comunicanteTextField.getText();
    }
    
    public String getPoliza(){
        return polizaTextField.getText();
    }
    
    public String getNombrePaciente(){
        return nombrePacienteTextField.getText();
    }
    
    public String getApellidosPaciente(){
        return apellidosPacienteTextField.getText();
    }
    
    public String getSexo(){
        return filtroSexo.getSelectedItem().toString();
    }
    
    
    public String getFechaNacimiento(){
        return fechaNacimientoTextField.getText();
    }
    
    public void setMensajeConsejos(String msj){
        mensajeConsejos.setText(msj);
    }
    
    public void resetearConsejo(){
        resultadoConsejoTextField.setText("");
        descripcionConsejoTextField.setText("");
    }
    
    public boolean getRequiereOperativo(){
        return requiereOperativo.getState();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAtenderLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAtenderLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAtenderLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAtenderLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAtenderLlamada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosPacienteTextField;
    private javax.swing.JToggleButton botonConfirmarDatos;
    private javax.swing.JToggleButton botonGuardarConsejo;
    private javax.swing.JToggleButton botonIntroducirDescripcion;
    private javax.swing.JToggleButton botonRegistrarLlamadaEntrante;
    private javax.swing.JTextField comunicanteTextField;
    private java.awt.Checkbox criticaCheck;
    private javax.swing.JTextField descripcionConsejoTextField;
    private javax.swing.JTextArea descripcionTextField;
    private javax.swing.JTextField fechaNacimientoTextField;
    private javax.swing.JComboBox<String> filtroSexo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeConsejos;
    private javax.swing.JLabel mensajeErr;
    private javax.swing.JTextField nombrePacienteTextField;
    private javax.swing.JPanel panelConfirmarDatos;
    private javax.swing.JPanel panelConsejos;
    private javax.swing.JPanel panelDescripcionEmergencia;
    private javax.swing.JTextField polizaTextField;
    private java.awt.Checkbox requiereOperativo;
    private javax.swing.JTextField resultadoConsejoTextField;
    private java.awt.Checkbox solucionaCheck;
    private javax.swing.JTextField telefOrigenTextField;
    // End of variables declaration//GEN-END:variables
}
